name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        for path in $(git diff --name-only '${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}' | grep / | cut -d/ -f1 | grep -v -e .github | sort -u); do
          echo ::group::build image ${path}
          docker build ${path}
          echo ::endgroup::
        done